### ISSUE TITLE
Docker image inherit from alpine

### ISSUE THREAD

**Issue by tfonfara** [tombowditch/telly#105]
Hey there,

first of all, thanks for all the hard work, I really appreciate it!

Would it be possible to let the docker image inherit from alpine instead of scratch? It wouldn't increase the size dramatically but would add some essential things like for example a bash. Tried to get network information of my telly container but failed badly^^

Also currently the automatically built docker images are not tagged, there is only the "latest" tag available: https://hub.docker.com/r/tombowditch/telly/tags/
It would be nice to have the different versions tagged there like 0.5, 0.6... so it would be possible then to pick a specific version and update containers.

Cheers!

**Comment by HazCod** [comment]
Hi, for network related stuff you can use `docker inspect`.
For the tagging, i'm bringing in @tombowditch

**Comment by tfonfara** [comment]
Unfortunately docker inspect isn't really working, e.g. if I call `docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' telly` it just returns nothing.

**Comment by HazCod** [comment]
How did you run telly? What are your docker networks?

**Comment by tfonfara** [comment]
I run telly with docker compose:

```
version: '2'
services:
  telly:
    container_name: telly
    image: tombowditch/telly
    restart: unless-stopped
    environment:
      - PLAYLIST=/config/playlist.m3u
      - LISTEN=0.0.0.0:6077
    volumes:
      - /docker-volumes/telly:/config
```

But nevertheless, even if docker inspect would show me the ip address it would only show the internal address, not the external one.
