### ISSUE TITLE
Unable to tune channel, variables, & log location

### ISSUE THREAD

**Issue by robflate** [tombowditch/telly#112]
This refers to using Telly on Docker.

I setup telly in Docker, successfully added it to Plex and mapped the channels. Plex downloaded guide data but all the channels show "Unable to tune channel". This used to work and I'm not sure what changed. The .m3u and .ts works in VLC.

Some observations;

1. Should the environment variables have quotes around them? I've seen [some people](https://github.com/tombowditch/telly/issues/82#issuecomment-382216228) say that putting quotes round their .m3u file in the docker compose file works. In my case, using quotes results in an error saying Telly can't read the m3u. What is the correct method for all the variables?
2. What is the purpose of the /tmp folder. Should it contain the m3u file that Telly parses? The volume mounted on my local file system is empty.
3. Do you have an example of a docker compose file with examples of all the environment variables in use?
4. The readme suggests the Telly tuner won't be found automatically but when I first add a tuner in Plex it is found alongside my HDHomeRun. They both then disappear after a few seconds and I add it manually. 
![screen shot 2018-06-15 at 13 56 49 2](https://user-images.githubusercontent.com/4172375/41469369-c87e5a8c-70a4-11e8-81be-0333b4891205.png)
5. From what I can tell, Plex DVR only seems to allow you to select a built in EPG from a single country. Obviously, most IPTV services have channels from around the world. This seems like a shortcoming of Plex rather than Telly but I wondered if anyone had a solution (add multiple Tuners?)
6. When I go to `Settings > Server > Live TV & DVR` in Plex I often see `Device not found. Ensure your device is powered on and connected to your network` next to the Telly tuner which means I can't see the link that allows me to remap channels. It's usually a clickable line of text that says how many channels I have. This happens even if Telly is successfully running in Docker. 
![plex 2018-06-13 13-23-55](https://user-images.githubusercontent.com/4172375/41469350-bafe70e0-70a4-11e8-870c-08ac18c453ae.png)
7. Where can I find the full telly logs (I'm using Docker for Mac and I can only seem to see the logs that Kitematic displays in the gui)?
8. Is anyone using Flawless? The URL doesn't work in Telly and I can't download with curl. The format I'm using is `http://portal.flawless-hosting.solutions/get.php?username=XXXXX&password=XXXXX&type=m3u_plus&output=ts`. As a workaround I'm using [Xtream-Editor](https://xtream-editor.com/) with Flawless and that works in Telly. Anyone know a Flawless URL that isn't domain blocked?

Here's my `docker-compose.yml`;

```
telly:
    image: tombowditch/telly
    container_name: telly
    hostname: telly
    ports:
      - "6077:6077"
    volumes:
      - ${CONFIG}/telly:/tmp
    environment:
      - PUID
      - PGID
      - TZ
      - PLAYLIST=http://xtream-editor.com/en/get/m3u/XXXXXXXXXXXX
      - USEREGEX="USA|UK|International Sport"
      - LISTEN=telly:6077
      - STREAMS=1
      - FRIENDLYNAME=Tuner1
      - DEVICEID=12345678
      - TEMP=/tmp
    labels:
      traefik.enable: "true"
      traefik.port: "6077"
      traefik.frontend.rule: "Host:telly.${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
```
and here are the logs that show in Kitematic;

```
[telly] [info] booting telly v0.6.2
[telly] [info] Downloading file http://xtream-editor.com/en/get/m3u/XXXXXXXXXXXX to /telly.m3u
[telly] [info] Reading m3u file /telly.m3u...
[telly] [warning] telly is not attempting to strip out unneeded channels, please use the flag -filterregex if telly returns too many channels
[telly] [info] telly is currently not filtering for only uk television. if you would like it to, please use the flag -uktv
[telly] [info] found 210 channels
[telly] [info] creating discovery data
[telly] [info] creating lineup status
[telly] [info] creating device xml
[telly] [info] creating webserver routes
[telly] [info] Building lineup
[telly] [info] advertising telly service on network
[telly] [debug] Advertising telly as HDHomerun (Tuner1) (12345678-AE2A-4E54-BBC9-33AF7D5D6A92)
[telly] [info] listening on telly:6077
```

Thanks.

**Comment by OmgImAlexis** [comment]
Duplicate: https://github.com/tombowditch/telly/issues/108

**Comment by robflate** [comment]
Following advice from @OmgImAlexis, Telly is now working without any unable to tune channel errors. I added `command: -base=192.168.0.39:6077` to my docker-compose file. The IP is my host IP. My docker compose-file now looks like this;

```
  telly:
    image: tombowditch/telly
    container_name: telly
    hostname: telly
    ports:
      - "6077:6077"
    volumes:
      - ${CONFIG}/telly:/tmp
    environment:
      - PUID
      - PGID
      - TZ
      - PLAYLIST=http://xtream-editor.com/en/get/m3u/XXXXXX
      - USEREGEX="USA|UK|International Sport"
      - LISTEN=telly:6077
      - STREAMS=1
      - FRIENDLYNAME=Tuner1
      - DEVICEID=12345678
      - TEMP=/tmp
    command: -base=192.168.0.39:6077
    labels:
      traefik.enable: "true"
      traefik.port: "6077"
      traefik.frontend.rule: "Host:telly.${DOMAIN}"
      traefik.frontend.auth.basic: "${HTPASSWD}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
```
