### ISSUE TITLE
Channels with dots

### ISSUE THREAD

**Issue by madasus** [tombowditch/telly#263]
**telly release with the issue:**
version=1.1.0.6, branch=dev

**Last working telly release (if known):**

**Operating environment (Docker/Windows/Linux/QNAP, etc.):**

Docker on Synology NAS

**Description of problem:**
I am retrieving a m3u file and xml epg from TVHeadend and I have channels that contain a dot in the channel number.  For example 8.1 and 8.2.  When these channels are loaded to Telly they come in without a channel number and are assigned a default (10000 range) channel. 

**Contents of `telly.config.toml` [if you're using a version above 1.1]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```toml
# THIS SECTION IS REQUIRED ########################################################################
[Discovery]                                    # most likely you won't need to change anything here
  Device-Auth = "telly123"                     # These settings are all related to how telly identifies
  Device-ID = "12345678"                       # itself to Plex.
  Device-UUID = ""
  Device-Firmware-Name = "hdhomeruntc_atsc"
  Device-Firmware-Version = "20150826"
  Device-Friendly-Name = "telly"
  Device-Manufacturer = "Silicondust"
  Device-Model-Number = "HDTC-2US"
  SSDP = true

# Note on running multiple instances of telly
# There are three things that make up a "key" for a given Telly Virtual DVR:
# Device-ID [required], Device-UUID [optional], and port [required]
# When you configure your additional telly instances, change:
# the Device-ID [above] AND
# the Device-UUID [above, if you're entering one] AND
# the port [below in the "Web" section]

# THIS SECTION IS REQUIRED ########################################################################
[IPTV]
  Streams = 10               # number of simultaneous streams that the telly virtual DVR will provide
                            # This is often 1, but is set by your iptv provider; for example, 
                            # Vaders provides 5
  Starting-Channel = 10000  # When telly assigns channel numbers it will start here
  XMLTV-Channels = true     # if true, any channel numbers specified in your M3U file will be used.
# FFMpeg = true             # if this is uncommented, streams are buffered through ffmpeg; 
                            # ffmpeg must be installed and on your $PATH
                            # if you want to use this with Docker, be sure you use the correct docker image
# if you DO NOT WANT TO USE FFMPEG leave this commented; DO NOT SET IT TO FALSE
  
# THIS SECTION IS REQUIRED ########################################################################
[Log]
  Level = "debug"            # Only log messages at or above the given level. [debug, info, warn, error, fatal]
  Requests = true           # Log HTTP requests made to telly

# THIS SECTION IS REQUIRED ########################################################################
[Web]
  Base-Address = "10.2.1.99:6077"   # Set this to the IP address of the machine telly runs on
  Listen-Address = "0.0.0.0:6077" # this can stay as-is

# THIS SECTION IS NOT USEFUL ======================================================================
#[SchedulesDirect]           # If you have a Schedules Direct account, fill in details and then
                             # UNCOMMENT THIS SECTION
#  Username = ""             # This is under construction; no provider
#  Password = ""             # works with it at this time

# AT LEAST ONE SOURCE IS REQUIRED #################################################################
# DELETE OR COMMENT OUT SOURCES THAT YOU ARE NOT USING ############################################
# NONE OF THESE EXAMPLES WORK AS-IS; IF YOU DON'T CHANGE IT, DELETE IT ############################
#[[Source]]
#  Name = ""                 # Name is optional and is used mostly for logging purposes
#  Provider = "Iris"         # named providers currently supported are "area51" and "Iris"
# IF YOUR PROVIDER IS NOT ONE OF THE ABOVE, CONFIGURE IT AS A "Custom" PROVIDER; SEE BELOW
#  Username = "YOUR_IPTV_USERNAME"
#  Password = "YOUR_IPTV_PASSWORD"
  # THE FOLLOWING KEYS ARE OPTIONAL IN THEORY, REQUIRED IN PRACTICE
#  Filter = "YOUR|FILTER|*REGEX"
#  FilterKey = "group-title" # FilterKey normally defaults to whatever the provider file says is best, 
                            # otherwise you must set this.
#  FilterRaw = false         # FilterRaw will run your regex on the entire line instead of just specific keys.
#  Sort = "group-title"      # Sort will alphabetically sort your channels by the M3U key provided

#[[Source]]
#  Name = ""                    # Name is optional and is used mostly for logging purposes
#  Provider = "IPTV-EPG"        # DO NOT CHANGE THIS IF YOU ARE USING THIS PROVIDER
#  Username = "M3U-Identifier"  # From http://iptv-epg.com/[M3U-Identifier].m3u
#  Password = "XML-Identifier"  # From http://iptv-epg.com/[XML-Identifier].xml
  # NOTE: THOSE KEY NAMES DO NOT MAKE SENSE FOR THIS PROVIDER ################
  # THIS IS JUST AN IMPLEMENTATION DETAIL.  JUST GO WITH IT.
  # For this purpose, IPTV-EPG does not have a "username" and "password", HOWEVER,
  # telly's scaffolding for a "Named provider" does. Rather than special-casing this provider,
  # the username and password are used to hold the two required bits of information.
  # THIS IS JUST AN IMPLEMENTATION DETAIL.  JUST GO WITH IT.
  # NOTE: THOSE KEY NAMES DO NOT MAKE SENSE FOR THIS PROVIDER ################
  # THE FOLLOWING KEYS ARE OPTIONAL HERE; IF YOU"RE USING IPTV-EPG YOU'VE PROBABLY DONE YOUR
  # FILTERING THERE ALREADY
  # Filter = ""
  # FilterKey = ""
  # FilterRaw = false
  # Sort = ""

[[Source]]
  Name = "TVHeadEnd"                 # Name is optional and is used mostly for logging purposes
  Provider = "Custom"       # DO NOT CHANGE THIS IF YOU ARE ENTERING URLS OR FILE PATHS
                            # "Custom" is telly's internal identifier for this 'Provider'
                            # If you change it to "NAMEOFPROVIDER" telly's reaction will be
                            # "I don't recognize a provider called 'NAMEOFPROVIDER'."
  M3U = "http://10.2.1.111:9981/playlist/channels"  # These can be either URLs or fully-qualified paths.
  EPG = "http://10.2.1.111:9981/xmltv/channels"
  # THE FOLLOWING KEYS ARE OPTIONAL IN THEORY, REQUIRED IN PRACTICE
 # Filter = "Sports|Premium Movies|United States.*|USA"
 # FilterKey = "group-title" # FilterKey normally defaults to whatever the provider file says is best, 
                            # otherwise you must set this.
 # FilterRaw = false         # FilterRaw will run your regex on the entire line instead of just specific keys.
  Sort = "group-title"      # Sort will alphabetically sort your channels by the M3U key provided
# END TELLY CONFIG  ###############################################################################

```

**Command line used to run telly [if applicable]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```

```

**Docker run command used to run telly [if applicable]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```

```

**telly or docker log:**
```

```

**Additional information:**
***M3U FILE***

#EXTM3U
#EXTINF:-1 logo="http://10.2.1.111:9981/imagecache/1931" tvg-id="6333a35363b624de60ed42778ddbec96" tvg-chno="2",CBS HD
http://10.2.1.111:9981/stream/channelid/1403204451?profile=pass
#EXTINF:-1 logo="http://10.2.1.111:9981/imagecache/1944" tvg-id="ae5a700177008456ea63763050555fb9" tvg-chno="8.1",WTNH-DT
http://10.2.1.111:9981/stream/channelid/24140462?profile=pass

***XMLTV FILE***

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">
<tv generator-info-name="TVHeadend-4.3.0~pre+201911151751-0~built201911152018~gitd453f5b~ubuntu18.04.1" source-info-name="tvh-Tvheadend">
<channel id="ae5a700177008456ea63763050555fb9">
  <display-name>WTNH-DT</display-name>
  <display-name>8.1</display-name>
  <icon src="http://10.2.1.111:9981/imagecache/1944"/>
</channel>
<programme start="20191125200000 -0500" stop="20191125220000 -0500" channel="ae5a700177008456ea63763050555fb9">
  <title>Dancing With the Stars</title>
  <sub-title>Finale</sub-title>
  <desc>Four celebrity and pro-dancer couples return to the ballroom to compete and win the Mirrorball trophy.</desc>
  <episode-num system="xmltv_ns">27 . 10 .   </episode-num></programme>
</tv>
