### ISSUE TITLE
TvHeadEnd 4.3 m3u integration error - Synology Docker

### ISSUE THREAD

**Issue by darkeagl** [tombowditch/telly#274]
**telly release with the issue:**
1.1.0.6

**Last working telly release (if known):**
never worked

**Operating environment (Docker/Windows/Linux/QNAP, etc.):**
Docker on a Synology 918+ with latest DSM

**Description of problem:**
Tvheadend is running in version 4.3~221c29b on the same Synology as Telly and the export of the m3u is working when I try it. Only telly cant work with the format. Has the format parser changed or what can I change that it can work?
I havent changed any settings in tvh as I cant see anything for the m3u export.

**Contents of `telly.config.toml` [if you're using a version above 1.1]:**
```toml
# THIS SECTION IS REQUIRED ########################################################################
[Discovery]                                    # most likely you won't need to change anything here
  Device-Auth = "telly123"                     # These settings are all related to how telly identifies
  Device-ID = 12345678                         # itself to Plex.
  Device-UUID = ""
  Device-Firmware-Name = "hdhomeruntc_atsc"
  Device-Firmware-Version = "20150826"
  Device-Friendly-Name = "telly"
  Device-Manufacturer = "Silicondust"
  Device-Model-Number = "HDTC-2US"
  SSDP = true

# Note on running multiple instances of telly
# There are three things that make up a "key" for a given Telly Virtual Tuner:
# Device-ID [required], Device-UUID [optional], and port [required]
# When you configure your additional telly instances, change:
# the Device-ID [above] AND
# the Device-UUID [above, if you're entering one] AND
# the port [below in the "Web" section]

# THIS SECTION IS REQUIRED ########################################################################
[IPTV]
  Streams = 1               # number of simultaneous streams that telly virtual tuner will provide
                            # This is often 1, but is set by your iptv provider
  Starting-Channel = 10000  # When telly assigns channel numbers it will start here
  XMLTV-Channels = true     # if true, any channel numbers specified in your M3U file will be used.
  FFMpeg = true             # if this is uncommented, streams are buffered through ffmpeg; 
                            # ffmpeg must be installed and on your $PATH
                            # if you want to use this with Docker, be sure you use the correct docker image
# if you DO NOT WANT TO USE FFMPEG leave this commented; DO NOT SET IT TO FALSE [Issue #185]
  
# THIS SECTION IS REQUIRED ########################################################################
[Log]
  Level = "info"            # Only log messages at or above the given level. [debug, info, warn, error, fatal]
  Requests = true           # Log HTTP requests made to telly

# THIS SECTION IS REQUIRED ########################################################################
[Web]
  Base-Address = "127.0.0.1:6077"   # Set this to the IP address of the machine telly runs on AS SEEN BY PLEX
                                  # telly will be telling Plex to connect to URLs at this address.
                                  # DO NOT REMOVE THE PORT
                                  # Just change the 0.0.0.0 to your IP address.
  Listen-Address = "0.0.0.0:6077" # this can stay as-is

# AT LEAST ONE SOURCE IS REQUIRED #################################################################
# COPY/PASTE THIS BLOCK TO ADD MORE SOURCES #######################################################
# THIS EXAMPLE WILL NOT WORK AS-IS ################################################################
[[Source]]
  Name = ""                 # Name is optional and is used mostly for logging purposes
  Provider = "Custom"       # DO NOT CHANGE THIS
                            # "Custom" is telly's internal identifier for this 'Provider'
                            # If you change it to "SOMETHING ELSE", telly's reaction will be
                            # "I don't recognize a provider called 'SOMETHING ELSE'."
  M3U = "http://username:password@192.168.1.2:9981/playlist/channels.m3u"  # This can be either URL or fully-qualified path.
                            # This needs to be an M3Uplus file
                            # IT CANNOT BE A STREAM ADDRESS
                            # IT CANNOT BE AN M3U THAT LINKS TO ANOTHER M3U
  EPG = ""       # This can be either URL or fully-qualified path.
  # THE FOLLOWING KEYS ARE OPTIONAL IN THEORY, REQUIRED IN PRACTICE
  Filter = "YOUR_FILTER_REGULAR_EXPRESSION"
                            # Telly is written in Go, and uses the Go regular expression system, 
                            # which is limited compared to other regular expression parsers.
  FilterKey = "group-title" # Telly applies the regular expression to the contents of this key in the M3U.
  FilterRaw = false         # FilterRaw will run your regex on the entire line instead of just specific keys.
  Sort = "group-title"      # Sort will alphabetically sort your channels by the M3U key provided
# END TELLY CONFIG  ###############################################################################
```

**Docker run command used to run telly [if applicable]:**

**telly or docker log:**
```
INFO[2020-05-29T16:08:59Z] telly is preparing to go live (version=1.1.0.6, branch=dev, revision=741108cd2100cf9f4d3a13f771d1ebe5132baae6) 
INFO[2020-05-29T16:08:59Z] Loading M3U from http://XXXXXXX:XXXXXXX@192.168.1.2:9981/playlist/channels.m3u 
ERRO[2020-05-29T16:08:59Z] unable to parse m3u file                      error="malformed M3U provided"
ERRO[2020-05-29T16:08:59Z] error when preparing provider                 error="malformed M3U provided"
ERRO[2020-05-29T16:08:59Z] error when processing provider                error="malformed M3U provided"
INFO[2020-05-29T16:08:59Z] telly is live and on the air!                
INFO[2020-05-29T16:08:59Z] Broadcasting from http://0.0.0.0:6077/       
INFO[2020-05-29T16:08:59Z] EPG URL: http://0.0.0.0:6077/epg.xml  
```

**Additional information:**
