### ISSUE TITLE
Lack of ARM/ARM64 support

### ISSUE THREAD

**Issue by JoshuaVandaele** [tombowditch/telly#294]
**telly release with the issue:**
`tellytv/telly:dev`

**Last working telly release (if known):**
None

**Operating environment (Docker/Windows/Linux/QNAP, etc.):**
Docker

**Description of problem:**
Currently, the telly docker cannot be ran on ARM which makes it not usable on my raspberry pi. I'd like to see support for it implemented for future users.

**Contents of `telly.config.toml` [if you're using a version above 1.1]:**
N/A

**Command line used to run telly [if applicable]:**
N/A

**Docker run command used to run telly [if applicable]:**
```yaml
version: "3"

networks:
  networks_reverse_proxy:
    external: true

services:
  telly:
    image: tellytv/telly:dev
    container_name: telly
    ports:
      - "6077:6077"
    environment:
      TZ: Europe/Paris
    volumes:
    - ./config/telly.config.toml:/etc/telly/telly.config.toml
    restart: unless-stopped
    networks:
      - networks_reverse_proxy
```

**telly or docker log:**
```sh
folfy@raspberrypi:~/docker/telly $ docker compose down && docker compose up -d && docker compose logs -f
[+] Running 1/0
 ✔ Container telly  Removed                                                                                                                                                                    0.0s 
[+] Running 2/2
 ✔ telly 1 layers [⣿]      0B/0B      Pulled                                                                                                                                                   3.3s 
   ✔ ac81121605b4 Pull complete                                                                                                                                                                1.2s 
[+] Running 2/2
 ✔ Container telly                                                                                                                                      Started                                1.6s 
 ! telly The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
telly  | exec ./app: exec format error
telly exited with code 0
```

**Additional information:**
